<a href="https://colab.research.google.com/github/fawazdhianabil/Object-Oriented-Programming/blob/main/OOP_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Import Library**

In [73]:
import numpy as np
import pandas as pd
from scipy.stats import mode
from sklearn import datasets

#**Import Dataset IRIS**

In [80]:
iris = datasets.load_iris()
df = iris.data[:,:4]
df

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

#**Holdout/Train Test Split**

In [83]:
x = df
y = iris.target

In [84]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

#**K-Nearest Neighbors OOP**

In [127]:
class KNN:
  'program KNN dengan OOP'

  def __init__(self,x_latih,y_latih,k):
    self.x_latih = x_latih
    self.y_latih = y_latih
    self.k = k

  def euclidean(self,x1,x2):
    return np.sqrt(np.sum((x1-x2)**2))

  def hitung_jarak(self):
    hasil_euclid = [self.euclidean(x, y) for x,y in zip(self.x_latih,self.y_latih)]
    return hasil_euclid

  def urut(self):
    k_urut= np.argsort(self.hitung_jarak())[:self.k]
    return k_urut

  def kelas(self):
    kelas = [self.y_latih[i] for i in self.urut()]
    return kelas

  def kelas_final(self):
    kelas = mode(self.kelas()) 
    kelas = kelas.mode[0]
    return kelas

  def KNN_latih(self,x):
    hitung_euclid = [self.euclidean(x, y) for y in self.x_latih]
  
    k_urut = np.argsort(hitung_euclid)[: self.k]
  
    kelas = [self.y_latih[i] for i in k_urut]
  
    kelas = mode(kelas) 
    kelas = kelas.mode[0]
    return kelas


  def KNN_predict(self,x_uji):
    y_pred= [self.KNN_latih(x) for x in x_uji]
    return np.array(y_pred)

##**Testing**

In [134]:
knn_oop = KNN(x_latih=x_train,y_latih=y_train,Sk=3)
knn_oop

In [129]:
knn_oop.hitung_jarak()

[5.732364259186606,
 5.988321968631947,
 6.448255578061404,
 5.124451190127583,
 5.744562646538029,
 5.394441583704471,
 7.064700984472025,
 6.712674578735364,
 6.2048368229954285,
 5.885575587824865,
 6.024948132556827,
 5.8360945845659495,
 5.909314681077664,
 6.33798075099633,
 6.718630812896331,
 4.8218253804964775,
 5.791372894228103,
 6.141661013113635,
 5.028916384272063,
 6.067948582511226,
 5.641808220774612,
 7.098591409568521,
 6.886944169949397,
 5.48270006474912,
 5.237365750069399,
 5.384236250388721,
 3.872983346207417,
 5.267826876426369,
 7.395268757793729,
 5.61159513863928,
 6.585590330410782,
 5.937171043518958,
 4.954795656734998,
 5.863446085707619,
 5.623166367803819,
 5.6204981985585585,
 6.567343450741707,
 6.672330927044911,
 6.6385239323211,
 5.358171329847526,
 5.545268253204709,
 6.030754513325841,
 6.606814663663572,
 7.366138744281159,
 7.39459261893446,
 5.74978260458602,
 5.085272854036448,
 4.803123983409131,
 5.8966091951222275,
 6.401562309311689,
 6

In [130]:
knn_oop.urut()

array([26, 85, 64])

In [131]:
knn_oop.kelas()

[2, 1, 2]

In [132]:
knn_oop.kelas_final()

2

In [133]:
y_pred_oop = knn_oop.KNN_predict(x_uji=x_test)
y_pred_oop

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

#**K-Nearest Neighbors Sklearn**

In [94]:
from sklearn.neighbors import KNeighborsClassifier
knn_sklearn = KNeighborsClassifier(n_neighbors=3).fit(x_train,y_train)
y_pred_sklearn = knn_sklearn.predict(x_test)

In [95]:
y_pred_sklearn

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

#**KNN-OOP vs KNN-Sklearn**

In [135]:
def akurasi(y_test, y_pred):
  total = len(y_test)
  salah = sum((y_test - y_pred) != 0)
  return (total - salah) / total   

In [136]:
akurasi(y_test,y_pred_oop)

0.9666666666666667

In [137]:
akurasi(y_test,y_pred_sklearn,)

0.9666666666666667